### ISSUE TITLE
Queryable Sub-trees?

### ISSUE THREAD

**Issue by vassudanagunta** [armon/go-radix#10]
I see that the implementation is recursive, but this isn't exposed in the public API. For example it would be powerful to get a reference to a sub-tree and then to be able to query it the same as the root tree.

I don't have the time to deep dive into the implementation, so I was hoping you could answer this for me: *Is there any technical reason why non-root Nodes can't be exposed and queried like the root Node? Is there some quirk in the implementation that prevents this, that requires all queries to be made from the root?*

**Comment by pjebs** [comment]
@armon

**Comment by armon** [comment]
@vassudanagunta @pjebs Probably the biggest limitation is that the size of the tree is only tracked at the root to prevent overhead of every node needing to keep that metadata. If you wanted to query sub-trees, mostly it would work except for size accounting.
