### ISSUE TITLE
Does it support unicode?

### ISSUE THREAD

**Issue by zippoxer** [armon/go-radix#5]
Since go-radix stores characters as bytes instead of runes, I'd guess not. Or am I missing something?

**Comment by armon** [comment]
@zippoxer I think it should work, but it will encode using the UTF8 binary values since that is how Go maintains the string.

**Comment by armon** [comment]
Closing, but re-open if you have an issue.

**Comment by zippoxer** [comment]
This library is the least memory consuming from the 4-5 trie libraries I tested, and I'm really excited to give it a go ;-)

As far as I know, two different UTF-8 encoded characters can have the same first byte, but a different two or third byte. So, identifying characters only by the first byte should cause conflicts where different characters look the same at lookup time when they're really two characters in different languages.

I'm not sure how to test this. Hopefully I'll report if I find a way.

Thank you again for this library :)
