### ISSUE TITLE
[Question] Router any paths 

### ISSUE THREAD

**Issue by guiferpa** [armon/go-radix#6]
Hi,

__Before anything, great package__ :+1: 

I'm creating an personal web framework and I need to route my routes :smile:. I'm studying and find a possible solution, use radix tree, and found this package.

But I've a problem, how to route the path if I catch a path with parameters ?

Ex.:

```go

package main

import (
	"fmt"

	radix "github.com/armon/go-radix"
)

func main() {

	r := radix.New()

	r.Insert("/a/b/c/:d", 1)
	r.Insert("/a/b/n/:d", 2)
	r.Insert("/a/t/u/:i", 2)

	m, _, _ := r.LongestPrefix("/a/b/c/test")

	fmt.Println(m) // Don't match path

}

```

In this scene this code not match my path, but should. Can you help me, it is possible to do?

Tks

**Comment by csimplestring** [comment]
I think in this case you should exclude the 'test' from the tree node.
